//
// Created by M.Kojro on 12/8/2021.
//

#ifndef NEURAL_NETWORK_C__INCLUDE_LETTERSDATASET_H_
#define NEURAL_NETWORK_C__INCLUDE_LETTERSDATASET_H_

#endif  // NEURAL_NETWORK_C__INCLUDE_LETTERSDATASET_H_
