name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: change dir
      working-directory: cmake-build-debug
    - name: update cmake
      run: cmake
    - name: make
      run: make
    - name: run
      run: ./neural_network_c_
