name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd cmake-build-debug && update cmake
      run: cmake
    - name: make
      run: cmake-build-debug && make
    - name: run
      run: ./cmake-build-debug/neural_network_c_
